import type { Path } from "../types"

export const SAMPLE_PATHS: Omit<Path, "id" | "isActive">[] = [
  // 🧠 Mental Mastery
  {
    name: "🧩 Hunter’s Mind",
    description: "Master the art of strategic thinking through chess and strategy games.",
    domain: "Mental Mastery",
    difficulty: "intermediate",
    currentTitle: "Novice",
    nextTitle: "Amateur",
    associatedAttributes: ["intelligence", "resilience"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "chess-daily-1",
        name: "Tactics Trainer",
        description: "Solve 5 chess puzzles.",
        type: "daily",
        completed: false,
        xpReward: 30,
        attributeRewards: { intelligence: 10, resilience: 5 },
      },
      {
        id: "chess-daily-2",
        name: "Opening Explorer",
        description: "Study a new chess opening for 15 minutes.",
        type: "daily",
        completed: false,
        xpReward: 20,
        attributeRewards: { intelligence: 8 },
      },
      {
        id: "chess-weekly-1",
        name: "Tournament Prep",
        description: "Play 5 rapid chess games.",
        type: "weekly",
        completed: false,
        weeklyTarget: 5,
        weeklyProgress: 0,
        xpReward: 80,
        attributeRewards: { intelligence: 25, resilience: 15 },
      },
      {
        id: "chess-weekly-2",
        name: "Game Analysis",
        description: "Analyze 2 of your own games.",
        type: "weekly",
        completed: false,
        weeklyTarget: 2,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { intelligence: 15 },
      },
    ],
  },
  {
    name: "🧠 The Maze Architect",
    description: "Sharpen your logic and problem-solving skills.",
    domain: "Mental Mastery",
    difficulty: "intermediate",
    currentTitle: "Novice",
    nextTitle: "Solver",
    associatedAttributes: ["intelligence", "focus"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "logic-daily-1",
        name: "Puzzle Time",
        description: "Solve a logic puzzle or brain teaser.",
        type: "daily",
        completed: false,
        xpReward: 25,
        attributeRewards: { intelligence: 10 },
      },
      {
        id: "logic-daily-2",
        name: "Critical Thinking",
        description: "Reflect on a problem you faced today and how you solved it.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { focus: 5 },
      },
      {
        id: "logic-weekly-1",
        name: "Challenge Accepted",
        description: "Complete a challenging escape room or logic game.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 60,
        attributeRewards: { intelligence: 20, focus: 10 },
      },
    ],
  },
  {
    name: "📚 Ink of the Ancients",
    description: "Dive deep into literature and reading mastery.",
    domain: "Mental Mastery",
    difficulty: "beginner",
    currentTitle: "Reader",
    nextTitle: "Scholar",
    associatedAttributes: ["intelligence", "wisdom"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "reading-daily-1",
        name: "Daily Reading",
        description: "Read for 30 minutes.",
        type: "daily",
        completed: false,
        xpReward: 20,
        attributeRewards: { intelligence: 8 },
      },
      {
        id: "reading-daily-2",
        name: "Literary Reflection",
        description: "Write a short reflection on what you read.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { wisdom: 5 },
      },
      {
        id: "reading-weekly-1",
        name: "Book Club",
        description: "Discuss a book or article with someone.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { intelligence: 10, wisdom: 10 },
      },
    ],
  },
  {
    name: "🏛 Mindforge",
    description: "Excel in academics and study techniques.",
    domain: "Mental Mastery",
    difficulty: "intermediate",
    currentTitle: "Student",
    nextTitle: "Adept",
    associatedAttributes: ["intelligence", "discipline"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "study-daily-1",
        name: "Focused Study",
        description: "Study for 45 minutes without distractions.",
        type: "daily",
        completed: false,
        xpReward: 25,
        attributeRewards: { intelligence: 10, discipline: 8 },
      },
      {
        id: "study-daily-2",
        name: "Review Notes",
        description: "Summarize your notes from today.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { discipline: 5 },
      },
      {
        id: "study-weekly-1",
        name: "Mock Test",
        description: "Take a practice test or quiz.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 50,
        attributeRewards: { intelligence: 15, discipline: 10 },
      },
    ],
  },
  {
    name: "🗣 Tower of Babel",
    description: "Master new languages and communication.",
    domain: "Mental Mastery",
    difficulty: "intermediate",
    currentTitle: "Beginner",
    nextTitle: "Polyglot",
    associatedAttributes: ["intelligence", "adaptability"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "language-daily-1",
        name: "Language Practice",
        description: "Practice your target language for 20 minutes.",
        type: "daily",
        completed: false,
        xpReward: 20,
        attributeRewards: { intelligence: 8, adaptability: 5 },
      },
      {
        id: "language-daily-2",
        name: "Vocabulary Builder",
        description: "Learn 5 new words.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { intelligence: 5 },
      },
      {
        id: "language-weekly-1",
        name: "Conversation Session",
        description: "Have a 10-minute conversation in your target language.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { adaptability: 10 },
      },
    ],
  },
  {
    name: "🪞 The Infinite Mirror",
    description: "Explore philosophy and wisdom.",
    domain: "Mental Mastery",
    difficulty: "advanced",
    currentTitle: "Thinker",
    nextTitle: "Philosopher",
    associatedAttributes: ["wisdom", "reflection"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "philosophy-daily-1",
        name: "Philosophical Reading",
        description: "Read a philosophical text for 20 minutes.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { wisdom: 8 },
      },
      {
        id: "philosophy-daily-2",
        name: "Reflective Writing",
        description: "Write a paragraph reflecting on a philosophical idea.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { reflection: 5 },
      },
      {
        id: "philosophy-weekly-1",
        name: "Debate or Dialogue",
        description: "Engage in a philosophical discussion.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { wisdom: 10, reflection: 10 },
      },
    ],
  },
  {
    name: "🔒 The Mind Lock",
    description: "Train your memory and focus.",
    domain: "Mental Mastery",
    difficulty: "intermediate",
    currentTitle: "Novice",
    nextTitle: "Mnemonic",
    associatedAttributes: ["focus", "discipline"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "memory-daily-1",
        name: "Memory Drill",
        description: "Practice a memory technique for 10 minutes.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { focus: 8 },
      },
      {
        id: "memory-daily-2",
        name: "Distraction-Free Block",
        description: "Work for 25 minutes with no distractions.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { discipline: 5 },
      },
      {
        id: "memory-weekly-1",
        name: "Recall Challenge",
        description: "Memorize and recall a list of 20 items.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 35,
        attributeRewards: { focus: 10, discipline: 10 },
      },
    ],
  },

  // 🏋️ Physical Discipline
  {
    name: "🛡 Temple of Iron",
    description: "Build strength and resilience through gym training.",
    domain: "Physical Discipline",
    difficulty: "intermediate",
    currentTitle: "Rookie",
    nextTitle: "Lifter",
    associatedAttributes: ["physical", "resilience"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "gym-daily-1",
        name: "Strength Session",
        description: "Complete a 45-minute strength workout.",
        type: "daily",
        completed: false,
        xpReward: 40,
        attributeRewards: { physical: 15, resilience: 10 },
      },
      {
        id: "gym-daily-2",
        name: "Mobility Routine",
        description: "Do 10 minutes of stretching or mobility work.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { physical: 5 },
      },
      {
        id: "gym-weekly-1",
        name: "Progressive Overload",
        description: "Increase weight or reps in 2 exercises.",
        type: "weekly",
        completed: false,
        weeklyTarget: 2,
        weeklyProgress: 0,
        xpReward: 60,
        attributeRewards: { physical: 20, resilience: 10 },
      },
      {
        id: "gym-weekly-2",
        name: "Consistency Streak",
        description: "Complete all daily workouts for 5 days.",
        type: "weekly",
        completed: false,
        weeklyTarget: 5,
        weeklyProgress: 0,
        xpReward: 50,
        attributeRewards: { resilience: 15 },
      },
    ],
  },
  {
    name: "🏀 Flowstate Dribble",
    description: "Master basketball through flow and skill.",
    domain: "Physical Discipline",
    difficulty: "intermediate",
    currentTitle: "Beginner",
    nextTitle: "Baller",
    associatedAttributes: ["physical", "focus"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "basketball-daily-1",
        name: "Dribble Drills",
        description: "Practice dribbling for 20 minutes.",
        type: "daily",
        completed: false,
        xpReward: 20,
        attributeRewards: { physical: 8, focus: 5 },
      },
      {
        id: "basketball-daily-2",
        name: "Free Throws",
        description: "Shoot 50 free throws.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { focus: 5 },
      },
      {
        id: "basketball-weekly-1",
        name: "Pickup Game",
        description: "Play a full-court game.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { physical: 15, focus: 10 },
      },
    ],
  },
  {
    name: "⚽️ The Field General",
    description: "Lead and excel in football/soccer.",
    domain: "Physical Discipline",
    difficulty: "intermediate",
    currentTitle: "Player",
    nextTitle: "Captain",
    associatedAttributes: ["physical", "leadership"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "soccer-daily-1",
        name: "Ball Control",
        description: "Practice ball control for 20 minutes.",
        type: "daily",
        completed: false,
        xpReward: 20,
        attributeRewards: { physical: 8 },
      },
      {
        id: "soccer-daily-2",
        name: "Passing Drills",
        description: "Complete 50 accurate passes.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { leadership: 5 },
      },
      {
        id: "soccer-weekly-1",
        name: "Team Play",
        description: "Participate in a team match.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { leadership: 10 },
      },
    ],
  },
  {
    name: "⚡️ The Pulse Runner",
    description: "Achieve peak cardio and running performance.",
    domain: "Physical Discipline",
    difficulty: "beginner",
    currentTitle: "Runner",
    nextTitle: "Sprinter",
    associatedAttributes: ["physical", "endurance"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "running-daily-1",
        name: "Daily Run",
        description: "Run for at least 20 minutes.",
        type: "daily",
        completed: false,
        xpReward: 20,
        attributeRewards: { physical: 8, endurance: 5 },
      },
      {
        id: "running-daily-2",
        name: "Stretch & Recover",
        description: "Do a post-run stretching routine.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { endurance: 5 },
      },
      {
        id: "running-weekly-1",
        name: "Long Run",
        description: "Complete a 10km run.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 50,
        attributeRewards: { endurance: 15 },
      },
    ],
  },
  {
    name: "🥋 Way of the Flowing Blade",
    description: "Master martial arts and fluid movement.",
    domain: "Physical Discipline",
    difficulty: "advanced",
    currentTitle: "Student",
    nextTitle: "Warrior",
    associatedAttributes: ["physical", "discipline"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "martial-daily-1",
        name: "Form Practice",
        description: "Practice forms/kata for 20 minutes.",
        type: "daily",
        completed: false,
        xpReward: 20,
        attributeRewards: { physical: 8, discipline: 5 },
      },
      {
        id: "martial-daily-2",
        name: "Shadow Sparring",
        description: "Shadow spar for 10 minutes.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { discipline: 5 },
      },
      {
        id: "martial-weekly-1",
        name: "Sparring Session",
        description: "Participate in a sparring session.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { physical: 10, discipline: 10 },
      },
    ],
  },
  {
    name: "💃 The Body’s Verse",
    description: "Express yourself through dance.",
    domain: "Physical Discipline",
    difficulty: "beginner",
    currentTitle: "Dancer",
    nextTitle: "Performer",
    associatedAttributes: ["physical", "creativity"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "dance-daily-1",
        name: "Choreography Practice",
        description: "Practice a dance routine for 20 minutes.",
        type: "daily",
        completed: false,
        xpReward: 20,
        attributeRewards: { physical: 8, creativity: 5 },
      },
      {
        id: "dance-daily-2",
        name: "Freestyle Session",
        description: "Freestyle dance for 10 minutes.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { creativity: 5 },
      },
      {
        id: "dance-weekly-1",
        name: "Performance",
        description: "Record or perform a dance piece.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { creativity: 10 },
      },
    ],
  },

  // 🎨 Creative Arts
  {
    name: "🎞 Chrono Crafter",
    description: "Master the art of video editing.",
    domain: "Creative Arts",
    difficulty: "intermediate",
    currentTitle: "Editor",
    nextTitle: "Cutter",
    associatedAttributes: ["creativity", "focus"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "video-daily-1",
        name: "Clip Assembly",
        description: "Edit 10 minutes of raw footage.",
        type: "daily",
        completed: false,
        xpReward: 20,
        attributeRewards: { creativity: 8, focus: 5 },
      },
      {
        id: "video-daily-2",
        name: "Effect Experiment",
        description: "Try a new editing effect or transition.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { creativity: 5 },
      },
      {
        id: "video-weekly-1",
        name: "Project Publish",
        description: "Finish and publish a video project.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 50,
        attributeRewards: { creativity: 15 },
      },
    ],
  },
  {
    name: "📷 Lens of Truth",
    description: "Capture the world through photography.",
    domain: "Creative Arts",
    difficulty: "beginner",
    currentTitle: "Photographer",
    nextTitle: "Artist",
    associatedAttributes: ["creativity", "perception"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "photo-daily-1",
        name: "Photo Walk",
        description: "Take 10 photos on a walk.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { perception: 8 },
      },
      {
        id: "photo-daily-2",
        name: "Editing Practice",
        description: "Edit your favorite photo from today.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { creativity: 5 },
      },
      {
        id: "photo-weekly-1",
        name: "Photo Series",
        description: "Create a themed photo series.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { creativity: 10, perception: 10 },
      },
    ],
  },
  {
    name: "✒️ Inkweaver",
    description: "Express yourself through drawing and art.",
    domain: "Creative Arts",
    difficulty: "beginner",
    currentTitle: "Sketcher",
    nextTitle: "Artist",
    associatedAttributes: ["creativity", "focus"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "drawing-daily-1",
        name: "Daily Sketch",
        description: "Draw for 20 minutes.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { creativity: 8, focus: 5 },
      },
      {
        id: "drawing-daily-2",
        name: "Technique Practice",
        description: "Practice a new drawing technique.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { focus: 5 },
      },
      {
        id: "drawing-weekly-1",
        name: "Art Challenge",
        description: "Complete a weekly art challenge.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { creativity: 10 },
      },
    ],
  },
  {
    name: "🌀 The Glyphsmith",
    description: "Craft stunning visuals with graphic design.",
    domain: "Creative Arts",
    difficulty: "intermediate",
    currentTitle: "Designer",
    nextTitle: "Smith",
    associatedAttributes: ["creativity", "precision"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "design-daily-1",
        name: "Design Sprint",
        description: "Design a logo or icon.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { creativity: 8, precision: 5 },
      },
      {
        id: "design-daily-2",
        name: "Color Study",
        description: "Experiment with a new color palette.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { creativity: 5 },
      },
      {
        id: "design-weekly-1",
        name: "Portfolio Piece",
        description: "Add a new piece to your design portfolio.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { creativity: 10, precision: 10 },
      },
    ],
  },
  {
    name: "🎶 Sonic Alchemy",
    description: "Produce and compose music.",
    domain: "Creative Arts",
    difficulty: "intermediate",
    currentTitle: "Producer",
    nextTitle: "Composer",
    associatedAttributes: ["creativity", "discipline"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "music-daily-1",
        name: "Composition Practice",
        description: "Write or produce music for 20 minutes.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { creativity: 8, discipline: 5 },
      },
      {
        id: "music-daily-2",
        name: "Instrument Session",
        description: "Practice an instrument for 15 minutes.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { discipline: 5 },
      },
      {
        id: "music-weekly-1",
        name: "Release Track",
        description: "Finish and share a new track.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { creativity: 10 },
      },
    ],
  },
  {
    name: "🎤 Voice of Echoes",
    description: "Master the art of singing.",
    domain: "Creative Arts",
    difficulty: "beginner",
    currentTitle: "Singer",
    nextTitle: "Vocalist",
    associatedAttributes: ["creativity", "confidence"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "singing-daily-1",
        name: "Vocal Warmup",
        description: "Do vocal warmups for 10 minutes.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { confidence: 5 },
      },
      {
        id: "singing-daily-2",
        name: "Song Practice",
        description: "Practice singing a song.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { creativity: 5 },
      },
      {
        id: "singing-weekly-1",
        name: "Performance",
        description: "Record or perform a song.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 30,
        attributeRewards: { confidence: 10 },
      },
    ],
  },
  {
    name: "🧿 Soul in Motion",
    description: "Bring characters to life through animation.",
    domain: "Creative Arts",
    difficulty: "advanced",
    currentTitle: "Animator",
    nextTitle: "Director",
    associatedAttributes: ["creativity", "focus"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "animation-daily-1",
        name: "Frame Practice",
        description: "Animate 10 new frames.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { creativity: 8, focus: 5 },
      },
      {
        id: "animation-daily-2",
        name: "Storyboard Sketch",
        description: "Sketch a storyboard for a scene.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { focus: 5 },
      },
      {
        id: "animation-weekly-1",
        name: "Short Animation",
        description: "Complete a short animation clip.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { creativity: 10 },
      },
    ],
  },

  // 💼 Work & Career
  {
    name: "📈 Architect of Ambition",
    description: "Build and grow your entrepreneurial vision.",
    domain: "Work & Career",
    difficulty: "advanced",
    currentTitle: "Founder",
    nextTitle: "Visionary",
    associatedAttributes: ["intelligence", "leadership"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "entrepreneur-daily-1",
        name: "Market Research",
        description: "Research your market or competitors for 20 minutes.",
        type: "daily",
        completed: false,
        xpReward: 20,
        attributeRewards: { intelligence: 8 },
      },
      {
        id: "entrepreneur-daily-2",
        name: "Networking",
        description: "Reach out to a potential partner or mentor.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { leadership: 5 },
      },
      {
        id: "entrepreneur-weekly-1",
        name: "Pitch Practice",
        description: "Practice your business pitch.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { leadership: 10 },
      },
    ],
  },
  {
    name: "💻 The Codebound",
    description: "Bend reality through the power of code.",
    domain: "Work & Career",
    difficulty: "advanced",
    currentTitle: "Script Kiddie",
    nextTitle: "Code Warrior",
    associatedAttributes: ["intelligence", "creativity"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "coding-daily-1",
        name: "Daily Coding",
        description: "Code for 1 hour on a personal project.",
        type: "daily",
        completed: false,
        xpReward: 35,
        attributeRewards: { intelligence: 12, creativity: 8 },
      },
      {
        id: "coding-daily-2",
        name: "Algorithm Practice",
        description: "Solve one algorithm challenge.",
        type: "daily",
        completed: false,
        xpReward: 25,
        attributeRewards: { intelligence: 10 },
      },
      {
        id: "coding-weekly-1",
        name: "Open Source Contribution",
        description: "Make a pull request to an open source repo.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 70,
        attributeRewards: { intelligence: 20, creativity: 10 },
      },
      {
        id: "coding-weekly-2",
        name: "Code Review",
        description: "Review and refactor code 2 times this week.",
        type: "weekly",
        completed: false,
        weeklyTarget: 2,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { intelligence: 10 },
      },
    ],
  },
  {
    name: "🧠 The Neural Oracle",
    description: "Master AI and data science.",
    domain: "Work & Career",
    difficulty: "advanced",
    currentTitle: "Analyst",
    nextTitle: "Oracle",
    associatedAttributes: ["intelligence", "creativity"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "ai-daily-1",
        name: "Model Practice",
        description: "Train or test a machine learning model.",
        type: "daily",
        completed: false,
        xpReward: 30,
        attributeRewards: { intelligence: 12 },
      },
      {
        id: "ai-daily-2",
        name: "Data Exploration",
        description: "Explore a new dataset.",
        type: "daily",
        completed: false,
        xpReward: 20,
        attributeRewards: { creativity: 8 },
      },
      {
        id: "ai-weekly-1",
        name: "Kaggle Challenge",
        description: "Submit a solution to a Kaggle competition.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 60,
        attributeRewards: { intelligence: 20 },
      },
    ],
  },
  {
    name: "⏳ The Flowchain",
    description: "Unlock peak productivity.",
    domain: "Work & Career",
    difficulty: "intermediate",
    currentTitle: "Worker",
    nextTitle: "Flowmaster",
    associatedAttributes: ["discipline", "focus"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "productivity-daily-1",
        name: "Deep Work Block",
        description: "Work for 60 minutes without distractions.",
        type: "daily",
        completed: false,
        xpReward: 25,
        attributeRewards: { discipline: 10, focus: 8 },
      },
      {
        id: "productivity-daily-2",
        name: "Task Review",
        description: "Review and plan tomorrow's tasks.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { focus: 5 },
      },
      {
        id: "productivity-weekly-1",
        name: "Weekly Review",
        description: "Reflect on your productivity for the week.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 30,
        attributeRewards: { discipline: 10 },
      },
    ],
  },
  {
    name: "💸 The Greedless Gambit",
    description: "Master investing and finance.",
    domain: "Work & Career",
    difficulty: "advanced",
    currentTitle: "Investor",
    nextTitle: "Strategist",
    associatedAttributes: ["intelligence", "discipline"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "finance-daily-1",
        name: "Market Watch",
        description: "Review market news and trends.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { intelligence: 8 },
      },
      {
        id: "finance-daily-2",
        name: "Portfolio Check",
        description: "Review your investment portfolio.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { discipline: 5 },
      },
      {
        id: "finance-weekly-1",
        name: "Investment Research",
        description: "Research a new investment opportunity.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { intelligence: 10, discipline: 10 },
      },
    ],
  },

  // 💫 Spiritual / Emotional Growth
  {
    name: "🕊 Soul of Serenity",
    description: "Cultivate peace through prayer and meditation.",
    domain: "Spiritual / Emotional Growth",
    difficulty: "beginner",
    currentTitle: "Seeker",
    nextTitle: "Serene",
    associatedAttributes: ["wisdom", "discipline"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "meditation-daily-1",
        name: "Meditation",
        description: "Meditate for 15 minutes.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { wisdom: 8, discipline: 5 },
      },
      {
        id: "meditation-daily-2",
        name: "Gratitude Practice",
        description: "Write down 3 things you're grateful for.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { wisdom: 5 },
      },
      {
        id: "meditation-weekly-1",
        name: "Silent Retreat",
        description: "Spend 1 hour in silence.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 30,
        attributeRewards: { discipline: 10 },
      },
    ],
  },
  {
    name: "🪞 Mirrorwalker",
    description: "Grow through self-reflection.",
    domain: "Spiritual / Emotional Growth",
    difficulty: "intermediate",
    currentTitle: "Reflector",
    nextTitle: "Walker",
    associatedAttributes: ["wisdom", "resilience"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "reflection-daily-1",
        name: "Daily Reflection",
        description: "Reflect on your day and write a short entry.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { wisdom: 8 },
      },
      {
        id: "reflection-daily-2",
        name: "Emotional Check-In",
        description: "Identify and name your emotions.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { resilience: 5 },
      },
      {
        id: "reflection-weekly-1",
        name: "Growth Review",
        description: "Review your progress and set a new intention.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 30,
        attributeRewards: { wisdom: 10 },
      },
    ],
  },
  {
    name: "🔥 Stoneheart Protocol",
    description: "Develop grit and stoicism.",
    domain: "Spiritual / Emotional Growth",
    difficulty: "advanced",
    currentTitle: "Initiate",
    nextTitle: "Stoneheart",
    associatedAttributes: ["resilience", "discipline"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "stoic-daily-1",
        name: "Stoic Reflection",
        description: "Reflect on a challenge and your response.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { resilience: 8 },
      },
      {
        id: "stoic-daily-2",
        name: "Cold Exposure",
        description: "Take a cold shower or do cold exposure.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { discipline: 5 },
      },
      {
        id: "stoic-weekly-1",
        name: "Adversity Challenge",
        description: "Intentionally do something difficult.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { resilience: 10, discipline: 10 },
      },
    ],
  },
  {
    name: "📓 The Archive of Becoming",
    description: "Transform through journaling.",
    domain: "Spiritual / Emotional Growth",
    difficulty: "beginner",
    currentTitle: "Writer",
    nextTitle: "Archivist",
    associatedAttributes: ["wisdom", "focus"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "journal-daily-1",
        name: "Journal Entry",
        description: "Write a journal entry.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { wisdom: 5 },
      },
      {
        id: "journal-daily-2",
        name: "Prompt Response",
        description: "Answer a self-discovery prompt.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { focus: 5 },
      },
      {
        id: "journal-weekly-1",
        name: "Weekly Recap",
        description: "Summarize your week in your journal.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 20,
        attributeRewards: { wisdom: 10 },
      },
    ],
  },
  {
    name: "🕯 The Hollow Path",
    description: "Practice discipline through fasting.",
    domain: "Spiritual / Emotional Growth",
    difficulty: "advanced",
    currentTitle: "Faster",
    nextTitle: "Ascetic",
    associatedAttributes: ["discipline", "resilience"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "fasting-daily-1",
        name: "Fasting Window",
        description: "Complete your daily fasting window.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { discipline: 8 },
      },
      {
        id: "fasting-daily-2",
        name: "Mindful Eating",
        description: "Eat a meal mindfully.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { resilience: 5 },
      },
      {
        id: "fasting-weekly-1",
        name: "Extended Fast",
        description: "Complete a 24-hour fast.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { discipline: 10, resilience: 10 },
      },
    ],
  },

  // 🍳 Lifestyle & Habit
  {
    name: "🍳 Alchemy of Taste",
    description: "Master the art of cooking.",
    domain: "Lifestyle & Habit",
    difficulty: "beginner",
    currentTitle: "Cook",
    nextTitle: "Chef",
    associatedAttributes: ["creativity", "discipline"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "cooking-daily-1",
        name: "Cook a Meal",
        description: "Cook a healthy meal.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { creativity: 8 },
      },
      {
        id: "cooking-daily-2",
        name: "Recipe Exploration",
        description: "Try a new recipe or ingredient.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { discipline: 5 },
      },
      {
        id: "cooking-weekly-1",
        name: "Meal Prep",
        description: "Prepare meals for the week.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 30,
        attributeRewards: { discipline: 10 },
      },
    ],
  },
  {
    name: "🧼 Sanctum of Stillness",
    description: "Create order through cleaning and organizing.",
    domain: "Lifestyle & Habit",
    difficulty: "beginner",
    currentTitle: "Organizer",
    nextTitle: "Sanctifier",
    associatedAttributes: ["discipline", "focus"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "cleaning-daily-1",
        name: "Tidy Up",
        description: "Spend 10 minutes tidying your space.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { discipline: 5 },
      },
      {
        id: "cleaning-daily-2",
        name: "Organize",
        description: "Organize one area (desk, shelf, etc).",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { focus: 5 },
      },
      {
        id: "cleaning-weekly-1",
        name: "Deep Clean",
        description: "Deep clean a room or area.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 30,
        attributeRewards: { discipline: 10 },
      },
    ],
  },
  {
    name: "🌙 The Dreamsmith",
    description: "Optimize your sleep for peak performance.",
    domain: "Lifestyle & Habit",
    difficulty: "beginner",
    currentTitle: "Sleeper",
    nextTitle: "Dreamsmith",
    associatedAttributes: ["discipline", "resilience"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "sleep-daily-1",
        name: "Sleep Routine",
        description: "Follow your sleep routine.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { discipline: 5 },
      },
      {
        id: "sleep-daily-2",
        name: "No Screens",
        description: "No screens 30 minutes before bed.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { resilience: 5 },
      },
      {
        id: "sleep-weekly-1",
        name: "Sleep Log",
        description: "Track your sleep for the week.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 20,
        attributeRewards: { discipline: 10 },
      },
    ],
  },
  {
    name: "💧 Core Renewal",
    description: "Build healthy daily habits.",
    domain: "Lifestyle & Habit",
    difficulty: "beginner",
    currentTitle: "Renewal",
    nextTitle: "Core",
    associatedAttributes: ["discipline", "resilience"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "habit-daily-1",
        name: "Hydration",
        description: "Drink 8 glasses of water.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { discipline: 5 },
      },
      {
        id: "habit-daily-2",
        name: "Step Count",
        description: "Walk at least 7,000 steps.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { resilience: 5 },
      },
      {
        id: "habit-weekly-1",
        name: "Habit Streak",
        description: "Complete all daily habits for 5 days.",
        type: "weekly",
        completed: false,
        weeklyTarget: 5,
        weeklyProgress: 0,
        xpReward: 30,
        attributeRewards: { discipline: 10 },
      },
    ],
  },
  {
    name: "🧥 Weaver of Impressions",
    description: "Express yourself through fashion and style.",
    domain: "Lifestyle & Habit",
    difficulty: "beginner",
    currentTitle: "Stylist",
    nextTitle: "Impressionist",
    associatedAttributes: ["creativity", "confidence"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "fashion-daily-1",
        name: "Outfit Planning",
        description: "Plan your outfit for the next day.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { creativity: 5 },
      },
      {
        id: "fashion-daily-2",
        name: "Style Inspiration",
        description: "Find and save a style inspiration.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { confidence: 5 },
      },
      {
        id: "fashion-weekly-1",
        name: "Wardrobe Refresh",
        description: "Organize or update your wardrobe.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 20,
        attributeRewards: { creativity: 10 },
      },
    ],
  },

  // 🧬 Wildcard / Hybrid Evolution
  {
    name: "🌐 Polymath’s Descent",
    description: "Master many skills and domains.",
    domain: "Wildcard / Hybrid Evolution",
    difficulty: "advanced",
    currentTitle: "Learner",
    nextTitle: "Polymath",
    associatedAttributes: ["intelligence", "adaptability"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "poly-daily-1",
        name: "Skill Rotation",
        description: "Practice a different skill each day.",
        type: "daily",
        completed: false,
        xpReward: 20,
        attributeRewards: { intelligence: 8, adaptability: 8 },
      },
      {
        id: "poly-daily-2",
        name: "Cross-Discipline Study",
        description: "Read about a field outside your comfort zone.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { adaptability: 5 },
      },
      {
        id: "poly-weekly-1",
        name: "Project Fusion",
        description: "Combine two skills in a single project.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 40,
        attributeRewards: { intelligence: 10, adaptability: 10 },
      },
    ],
  },
  {
    name: "🕷 Abyss Diver",
    description: "Overcome fear and embrace challenge.",
    domain: "Wildcard / Hybrid Evolution",
    difficulty: "advanced",
    currentTitle: "Diver",
    nextTitle: "Abyssal",
    associatedAttributes: ["resilience", "courage"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "fear-daily-1",
        name: "Face a Fear",
        description: "Do something that scares you (big or small).",
        type: "daily",
        completed: false,
        xpReward: 20,
        attributeRewards: { resilience: 8, courage: 8 },
      },
      {
        id: "fear-daily-2",
        name: "Reflection",
        description: "Reflect on how you handled fear today.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { courage: 5 },
      },
      {
        id: "fear-weekly-1",
        name: "Major Challenge",
        description: "Tackle a major fear or challenge.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 50,
        attributeRewards: { resilience: 15, courage: 15 },
      },
    ],
  },
  {
    name: "🔁 The Rebirth Directive",
    description: "Reinvent yourself and your habits.",
    domain: "Wildcard / Hybrid Evolution",
    difficulty: "advanced",
    currentTitle: "Changer",
    nextTitle: "Reborn",
    associatedAttributes: ["adaptability", "discipline"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "rebirth-daily-1",
        name: "New Habit",
        description: "Start or reinforce a new habit.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { adaptability: 8 },
      },
      {
        id: "rebirth-daily-2",
        name: "Let Go",
        description: "Identify and let go of an old habit or belief.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { discipline: 5 },
      },
      {
        id: "rebirth-weekly-1",
        name: "Transformation Log",
        description: "Document your transformation journey.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 30,
        attributeRewards: { adaptability: 10, discipline: 10 },
      },
    ],
  },
  {
    name: "🗿 Obsidian Will",
    description: "Develop self-discipline across all fields.",
    domain: "Wildcard / Hybrid Evolution",
    difficulty: "advanced",
    currentTitle: "Willed",
    nextTitle: "Obsidian",
    associatedAttributes: ["discipline", "resilience"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "will-daily-1",
        name: "Discipline Drill",
        description: "Complete a task you want to avoid.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { discipline: 8, resilience: 5 },
      },
      {
        id: "will-daily-2",
        name: "Consistency",
        description: "Stick to your daily routine.",
        type: "daily",
        completed: false,
        xpReward: 10,
        attributeRewards: { resilience: 5 },
      },
      {
        id: "will-weekly-1",
        name: "No Zero Days",
        description: "Have no zero days this week.",
        type: "weekly",
        completed: false,
        weeklyTarget: 7,
        weeklyProgress: 0,
        xpReward: 50,
        attributeRewards: { discipline: 15 },
      },
    ],
  },
  {
    name: "🦋 Ascendant Protocol",
    description: "Pursue your ultimate form and final goal.",
    domain: "Wildcard / Hybrid Evolution",
    difficulty: "advanced",
    currentTitle: "Seeker",
    nextTitle: "Ascendant",
    associatedAttributes: ["all"],
    totalXP: 0,
    completionRate: 0,
    prerequisites: [
      {
        id: "ascendant-daily-1",
        name: "Ultimate Practice",
        description: "Work on your highest goal for 30 minutes.",
        type: "daily",
        completed: false,
        xpReward: 30,
        attributeRewards: { all: 10 },
      },
      {
        id: "ascendant-daily-2",
        name: "Reflect & Refine",
        description: "Reflect and refine your approach.",
        type: "daily",
        completed: false,
        xpReward: 15,
        attributeRewards: { all: 5 },
      },
      {
        id: "ascendant-weekly-1",
        name: "Milestone",
        description: "Achieve a milestone toward your final form.",
        type: "weekly",
        completed: false,
        weeklyTarget: 1,
        weeklyProgress: 0,
        xpReward: 100,
        attributeRewards: { all: 25 },
      },
    ],
  },
]

// --- Helper functions for resetting tasks ---

/** Resets all daily tasks to not completed. */
export function resetDailyTasks(paths: Omit<Path, "id" | "isActive">[]) {
  paths.forEach(path => {
    path.prerequisites.forEach(task => {
      if (task.type === "daily") {
        task.completed = false
      }
    })
  })
}

/** Resets all weekly tasks' progress and completion. */
export function resetWeeklyTasks(paths: Omit<Path, "id" | "isActive">[]) {
  paths.forEach(path => {
    path.prerequisites.forEach(task => {
      if (task.type === "weekly") {
        task.completed = false
        if ("weeklyProgress" in task) task.weeklyProgress = 0
      }
    })
  })
}
